const fixedMinePool = artifacts.require("fixedMinePool_Timed");
const CFNX = artifacts.require("CFNX");
const BN = require("bn.js");
const minePoolProxy = artifacts.require("testMinePoolProxy");
let PeriodTime = 90*86400;
const {migrateTimedMinePool,migrateTestMinePool} = require("./testFunctions.js")
contract('fixedMinePool_Timed', function (accounts){
    it('fixedMinePool_Timed one person mined', async function (){
        let contracts = await migrateTimedMinePool(accounts);
        let nowId = await contracts.minePool.getCurrentPeriodID();
        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        await contracts.minePool.stakeFPTA(100000);
        await contracts.minePool.stakeFPTB(100000,2);
        await contracts.minePool.setMineCoinInfo(contracts.MINE.address,2000000,1);
        let userPeriodId = await contracts.minePool.getUserMaxPeriodId(accounts[0]);
        assert.equal(userPeriodId.toNumber(),nowId.toNumber()+1,"getUserMaxPeriodId Error");
        await contracts.minePool.setTime(5);
        nowId = await contracts.minePool.getCurrentPeriodID();

        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        let mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        let realMine = 2000000*5*6;

        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        let allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.setTime(10);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 2000000*10*6;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.setTime(15);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 2000000*10*6 + 2000000*5*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.setTime(20);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 2000000*10*6 + 2000000*10*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.setTime(25);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 2000000*10*6 + 2000000*10*5 + 2000000*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.setTime(55);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 2000000*10*6 + 2000000*10*5 + 2000000*35;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.redeemMinerCoin(contracts.MINE.address,mineBalance);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");
        let oldMine = allMine.toNumber();
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert.equal(allMine.toNumber(),oldMine,"getTotalMined error");
    });
    it('fixedMinePool_Timed two persons mined', async function (){
        let contracts = await migrateTimedMinePool(accounts);
        let nowId = await contracts.minePool.getCurrentPeriodID();
        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        await contracts.minePool.stakeFPTA(100000);
        await contracts.minePool.stakeFPTB(100000,2);
        await contracts.minePool.setMineCoinInfo(contracts.MINE.address,2000000,1);
        let userPeriodId = await contracts.minePool.getUserMaxPeriodId(accounts[0]);
        assert.equal(userPeriodId.toNumber(),nowId.toNumber()+1,"getUserMaxPeriodId Error");
        await contracts.minePool.setTime(5);
        nowId = await contracts.minePool.getCurrentPeriodID();
        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        let mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        let realMine = 2000000*5*6;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.stakeFPTA(100000,{from:accounts[1]});
        await contracts.minePool.stakeFPTB(100000,4,{from:accounts[1]});
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");
        await contracts.minePool.setTime(10);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        let realMineB = 40000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(15);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*5*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*5*7;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(20);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(25);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*5*6;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(35);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*15;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*5*5;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(45);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*25;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*10*5 +5000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(55);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*35;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        await contracts.minePool.redeemMinerCoin(contracts.MINE.address,mineBalance);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");

        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*10*5 +15000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        await contracts.minePool.redeemMinerCoin(contracts.MINE.address,mineBalance,{from:accounts[1]});
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
    });
    it('fixedMinePool_Timed two persons mined update contract', async function (){
        let contracts = await migrateTestMinePool(accounts);
        let nowId = await contracts.minePool.getCurrentPeriodID();
        console.log("getCurrentPeriodID : ",nowId.toNumber());
        minePool = await fixedMinePool.new(contracts.CFNXA.address,contracts.CFNXB.address,0);
        contracts.minePool.setImplementation(minePool.address);
        await contracts.minePool.stakeFPTA(100000);
        await contracts.minePool.stakeFPTB(100000,2);
        nowId = await contracts.minePool.getCurrentPeriodID();
        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        await contracts.minePool.setMineCoinInfo(contracts.MINE.address,2000000,1);
        let userPeriodId = await contracts.minePool.getUserMaxPeriodId(accounts[0]);
        assert.equal(userPeriodId.toNumber(),nowId.toNumber()+1,"getUserMaxPeriodId Error");
        await contracts.minePool.setTime(5);
        nowId = await contracts.minePool.getCurrentPeriodID();
        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        let mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        let realMine = 2000000*5*6;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.stakeFPTA(100000,{from:accounts[1]});
        await contracts.minePool.stakeFPTB(100000,4,{from:accounts[1]});
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");
        await contracts.minePool.setTime(10);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        let realMineB = 40000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(15);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*5*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*5*7;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(20);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(25);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*5*6;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(35);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*15;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*5*5;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(45);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*25;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*10*5 +5000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(55);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*35;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        await contracts.minePool.redeemMinerCoin(contracts.MINE.address,mineBalance);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");

        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*10*5 +15000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        await contracts.minePool.redeemMinerCoin(contracts.MINE.address,mineBalance,{from:accounts[1]});
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
    });
    it('fixedMinePool_Timed two persons mined update contract', async function (){
        let contracts = await MinePool(accounts);
        let nowId = await contracts.minePool.getCurrentPeriodID();
        console.log("getCurrentPeriodID : ",nowId.toNumber());
        await contracts.minePool.setMineCoinInfo(contracts.MINE.address,2000000,1);
        await contracts.minePool.setTime(5);
        await contracts.minePool.stakeFPTA(100000);
        await contracts.minePool.stakeFPTB(100000,2);
        nowId = await contracts.minePool.getCurrentPeriodID();
        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        let userPeriodId = await contracts.minePool.getUserMaxPeriodId(accounts[0]);
        assert.equal(userPeriodId.toNumber(),nowId.toNumber()+1,"getUserMaxPeriodId Error");
        await contracts.minePool.setTime(5+5);
        nowId = await contracts.minePool.getCurrentPeriodID();
        assert.equal(nowId.toNumber(),1,"getCurrentPeriodID Error");
        let mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        let realMine = 2000000*5*6;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-mineBalance.toNumber())<10,"getTotalMined error");
        await contracts.minePool.stakeFPTA(100000,{from:accounts[1]});
        await contracts.minePool.stakeFPTB(100000,4,{from:accounts[1]});
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");
        await contracts.minePool.setTime(10+5);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        let realMineB = 40000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(15+5);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*5*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*5*7;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(20+5);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(25+5);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*5;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*5*6;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(35+5);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*15;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*5*5;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(45+5);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*25;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*10*5 +5000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
        await contracts.minePool.setTime(55+5);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        realMine = 90000000+1000000*10*5 + 1000000*35;
        assert(Math.abs(mineBalance.toNumber()-realMine)<10,"getMinerBalance error");
        await contracts.minePool.redeemMinerCoin(contracts.MINE.address,mineBalance);
        mineBalance = await contracts.minePool.getMinerBalance(accounts[0],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");

        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        realMineB = 40000000+1000000*10*7 +1000000*10*6 + 1000000*10*5 +15000000;
        assert(Math.abs(mineBalance.toNumber()-realMineB)<10,"getMinerBalance error");
        await contracts.minePool.redeemMinerCoin(contracts.MINE.address,mineBalance,{from:accounts[1]});
        mineBalance = await contracts.minePool.getMinerBalance(accounts[1],contracts.MINE.address);
        assert.equal(mineBalance.toNumber(),0,"getMinerBalance error");
        allMine = await contracts.minePool.getTotalMined(contracts.MINE.address);
        assert(Math.abs(allMine.toNumber()-realMine-realMineB)<10,"getTotalMined error");
    });
});
async function MinePool(accounts){
    let CFNXA = await CFNX.new();
    let CFNXB = await CFNX.new();
    let USDC = await CFNX.new();
    let Mine = await CFNX.new();
    let startTime = 5;
    let minePoolImpl = await fixedMinePool.new(CFNXA.address,CFNXB.address,startTime);
    let minePool = await minePoolProxy.new(minePoolImpl.address,CFNXA.address,CFNXB.address,startTime);
    await CFNXA.mint(accounts[0],1000000000000000);
    await CFNXA.approve(minePool.address,1000000000000000);
    
    await CFNXB.mint(accounts[0],1000000000000000);
    await CFNXB.approve(minePool.address,1000000000000000);

    await CFNXA.mint(accounts[1],1000000000000000,);
    await CFNXA.approve(minePool.address,1000000000000000,{from:accounts[1]});
    await CFNXB.mint(accounts[1],1000000000000000);
    await CFNXB.approve(minePool.address,1000000000000000,{from:accounts[1]});
    await USDC.mint(accounts[0],1000000000000000);
    await USDC.approve(minePool.address,1000000000000000);
    await USDC.mint(accounts[1],1000000000000000);
    await USDC.approve(minePool.address,1000000000000000,{from:accounts[1]});
    await Mine.mint(minePool.address,1000000000000000);
    return {
        minePool : minePool,
        CFNXA : CFNXA,
        CFNXB : CFNXB,
        USDC : USDC,
        MINE : Mine
    }
}